GO
CREATE TABLE LOAIMATHANG(
MATLOAIMATHANG CHAR(10) PRIMARY KEY,
TENLOAIMATHANG VARCHAR(30)
);
GO

CREATE TABLE KHOANGTHOIGIAN(
MAKHOANGTHOIGIAN CHAR(10) PRIMARY KEY,
MOTA VARCHAR(20)
);
GO

CREATE TABLE DANGKYGIAOHANG(
MATHANHVIENGIAOHANG CHAR(10) PRIMARY KEY,
MAKHOANGTHOIGIANDKGIAOHANG CHAR(10),
FOREIGN KEY (MAKHOANGTHOIGIANDKGIAOHANG) REFERENCES KHOANGTHOIGIAN(MAKHOANGTHOIGIAN)
);
GO

CREATE TABLE KHUVUC(
MAKHUVUC CHAR(10) PRIMARY KEY,
TENKHUVUC VARCHAR(30)
);
GO

CREATE TABLE KHACHHANG(
MAKHACHHANG CHAR(10) PRIMARY KEY,
MAKHUVUC CHAR(10),
TENKHACHHANG VARCHAR(30),
TENCUAHANG VARCHAR(40),
SODTKHACHHANG INT,
DIACHIEMAIL VARCHAR(30),
DIACHINHANHANG VARCHAR(60),
FOREIGN KEY (MAKHUVUC) REFERENCES KHUVUC(MAKHUVUC)
);
GO

CREATE TABLE DICHVU(
MADICHVU CHAR(10) PRIMARY KEY,
TENDICHVU VARCHAR(30)
);
GO

CREATE TABLE THANHVIENGIAOHANG(
MATHANHVIENGIAOHANG CHAR(10) PRIMARY KEY,
TENTHANHVIENGIAOHANG VARCHAR(30),
NGAYSINH DATE,
GIOITINH CHAR(10),
SODTTHANHVIEN INT,
DIACHITHANHVIEN VARCHAR(60),
FOREIGN KEY (MATHANHVIENGIAOHANG) REFERENCES DANGKYGIAOHANG(MATHANHVIENGIAOHANG)
);
GO

CREATE TABLE DONHANGGIAOHANG(
MADONHANGGIAOHANG CHAR(10) PRIMARY KEY,
MAKHACHHANG CHAR(10),
MATHANHVIENGIAOHANG CHAR(10),
MADICHVU CHAR(10),
MAKHUVUCGIAOHANG CHAR(10),
TENNGUOINHAN VARCHAR(40),
DIACHIGIAOHANG VARCHAR(60),
SODTNGUOINHAN INT,
MAKHOANGTHOIGIANGIAOHANG CHAR(10),
NGAYGIAOHANG DATE,
PHUONGTHUCTHANHTOAN VARCHAR(20),
TRANGTHAIPHEDUYET VARCHAR(20),
TRANGTHAIGIAOHANG VARCHAR(20)
FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
FOREIGN KEY (MATHANHVIENGIAOHANG) REFERENCES THANHVIENGIAOHANG(MATHANHVIENGIAOHANG),
FOREIGN KEY (MADICHVU) REFERENCES DICHVU(MADICHVU),
FOREIGN KEY (MAKHUVUCGIAOHANG) REFERENCES KHUVUC(MAKHUVUC),
FOREIGN KEY (MAKHOANGTHOIGIANGIAOHANG) REFERENCES KHOANGTHOIGIAN(MAKHOANGTHOIGIAN)

);
GO

CREATE TABLE CHITIETDONHANG(
MADONHANGGIAOHANG CHAR(10),
TENSANPHAMDUOCGIAO CHAR(40) ,
SOLUONG INT,
TRONGLUONG DECIMAL(10,2),
MALOAIMATHANG CHAR(10),
TIENTHUHO DECIMAL(6,3),
PRIMARY KEY(MADONHANGGIAOHANG,TENSANPHAMDUOCGIAO),
FOREIGN KEY (MALOAIMATHANG) REFERENCES LOAIMATHANG(MATLOAIMATHANG),
FOREIGN KEY (MADONHANGGIAOHANG) REFERENCES DONHANGGIAOHANG(MADONHANGGIAOHANG)
);
GO

ALTER TABLE THANHVIENGIAOHANG
ALTER COLUMN SODTTHANHVIEN FLOAT;
ALTER TABLE THANHVIENGIAOHANG
ALTER COLUMN SODTTHANHVIEN VARCHAR(20);
ALTER TABLE KHACHHANG 
ALTER COLUMN SODTKHACHHANG VARCHAR(20);
ALTER TABLE CHITIETDONHANG
ALTER COLUMN TIENTHUHO DECIMAL(9,3);
GO
ALTER TABLE DONHANGGIAOHANG
ALTER COLUMN SODTNGUOINHAN VARCHAR(20);
GO



USE QUANLYGIAOHANGTPDANANG;
GO
--CAU 1:XOA KHACH TEN LA "Le Thi A" 
DELETE FROM KHACHHANG WHERE TENKHACHHANG = 'Le Thi A' AND MAKHACHHANG ='KH001';
GO
--CAU 2: cap nhat khach khu vuc "Son Tra" thanh " Ngu Hanh Son"
UPDATE KHACHHANG SET MAKHUVUC ='KV003' WHERE MAKHUVUC ='KV001';
GO

SELECT * FROM KHACHHANG;
GO

SELECT * FROM THANHVIENGIAOHANG;
GO

--CAU 3: liet ke Shipper co ten bat dau bang "TR" va co do dai 25 ky tu tinh ca ky tu trang
SELECT * FROM THANHVIENGIAOHANG WHERE TENTHANHVIENGIAOHANG LIKE 'TR%' 
AND LEN(TENTHANHVIENGIAOHANG)  > 25;
go

USE QUANLYGIAOHANGTPDANANG;
GO
--CAU 4: LIET KE DON HANG CO DATE TRONG NAM 2017 VA CO KHU VUC LA HAI CHAU
SELECT * FROM DONHANGGIAOHANG WHERE 
YEAR(DONHANGGIAOHANG.NGAYGIAOHANG) = 2017 AND MAKHUVUCGIAOHANG = 'KV004';
GO
SELECT * FROM DONHANGGIAOHANG;
GO
--CAU 5: TRANG THAI DA GIAO HANG , NGAYGIAOHANG GIAM DAN THEO PHUONGTHUCTHANHTOAN 
SELECT DHGH.MADONHANGGIAOHANG, DHGH.MATHANHVIENGIAOHANG, 
TVGH.TENTHANHVIENGIAOHANG, DHGH.NGAYGIAOHANG, DHGH.PHUONGTHUCTHANHTOAN 
FROM DONHANGGIAOHANG DHGH
JOIN THANHVIENGIAOHANG TVGH ON DHGH.MATHANHVIENGIAOHANG = TVGH.MATHANHVIENGIAOHANG
WHERE TRANGTHAIGIAOHANG = 'Da Giao Hang'  ORDER BY PHUONGTHUCTHANHTOAN;
GO

--CAU 6: LIET KE THANH VIEN NAM CHUA GIAO LAN NAO 
SELECT * FROM THANHVIENGIAOHANG
JOIN DONHANGGIAOHANG 
ON THANHVIENGIAOHANG.MATHANHVIENGIAOHANG = DONHANGGIAOHANG.MATHANHVIENGIAOHANG
WHERE GIOITINH='NAM' AND TRANGTHAIGIAOHANG = '';
GO
--CAU 7: LIET KE TEN KHACH HANG TRONG HE THONG , NEU TEN GIONG HIEN THI 1 LAN
SELECT DISTINCT TENKHACHHANG FROM KHACHHANG;
GO
--CAU 8: LIET KE TAT CA KHACH HANG TRONG HE THONG
SELECT DHGH.DIACHIGIAOHANG, DHGH.MADONHANGGIAOHANG,KH.MAKHACHHANG, KH.TENKHACHHANG, 
DHGH.PHUONGTHUCTHANHTOAN, DHGH.TRANGTHAIGIAOHANG FROM DONHANGGIAOHANG DHGH  
JOIN KHACHHANG KH ON DHGH.MAKHACHHANG = KH.MAKHACHHANG;
GO

--CAU 9: liet ke nhan vien giao hang la nu giao hang khac nhau o khu vuc "hai chau"
SELECT * FROM DONHANGGIAOHANG;
go
SELECT * FROM THANHVIENGIAOHANG
JOIN DONHANGGIAOHANG 
ON THANHVIENGIAOHANG.MATHANHVIENGIAOHANG = DONHANGGIAOHANG.MATHANHVIENGIAOHANG
WHERE  GIOITINH = 'nu' AND MAKHUVUCGIAOHANG ='KV005';
GO

--CAU 10: LIET KE KHACH HANG NHAN GIAO KHU VUC NGU HANH SON VA CHUA TUNG DUOC THANH VIEN NAM NHAN HANG
SELECT KHACHHANG.* FROM KHACHHANG 
JOIN DONHANGGIAOHANG 
ON KHACHHANG.MAKHACHHANG = DONHANGGIAOHANG.MAKHACHHANG
JOIN THANHVIENGIAOHANG 
ON DONHANGGIAOHANG.MATHANHVIENGIAOHANG = THANHVIENGIAOHANG.MATHANHVIENGIAOHANG
WHERE MAKHUVUC ='KV003' AND GIOITINH != 'nam';
